apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: obs
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    # ruler:
    #   alertmanager_url: http://alertmanager.monitoring.svc.cluster.local:9093

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h