apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-write
  namespace: obs
  labels:
    app: loki
    component: write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      component: write
  template:
    metadata:
      labels:
        app: loki
        component: write
    spec:
      securityContext:  # Add the securityContext
        runAsUser: 10001
        fsGroup: 10001
      containers:
      - name: loki
        image: grafana/loki:2.9.1
        args:
        - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9096
          name: grpc
        volumeMounts:
        - name: loki-config-vol
          mountPath: /etc/loki
        - name: loki-storage
          mountPath: /var/loki
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 45
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 45
          timeoutSeconds: 1
      volumes:
      - name: loki-config-vol
        configMap:
          name: loki-config
      - name: loki-storage
        persistentVolumeClaim:
          claimName: loki-storage