# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: loki-storage
#   namespace: obs
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi  # Adjust as needed
#   storageClassName: default # Or your specific storage class