# apiVersion: v1
# kind: Service
# metadata:
#   name: loki-read
#   namespace: obs
#   labels:
#     app: loki
#     component: read
#     object: logging
# spec:
#   ports:
#   - name: http
#     port: 3100
#     targetPort: http
#   - name: grpc
#     port: 9096
#     targetPort: grpc
#   selector:
#     app: loki
#     component: read
#   type: ClusterIP