# --- deployments.yaml ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  # namespace: default  # Default namespace is implicit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: saranrnair/frontend-service:v2 # Updated image reference
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ORDERS_SERVICE_URL
              value: "http://orders-service.default.svc.cluster.local:5000"
            - name: PRODUCTS_SERVICE_URL
              value: "http://products-service.default.svc.cluster.local:5001"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: saranrnair/orders-service:v2 # Updated image reference
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PRODUCTS_SERVICE_URL
              value: "http://products-service.default.svc.cluster.local:5001"
            - name: RECOMMENDATIONS_SERVICE_URL
              value: "http://recommendations-service.default.svc.cluster.local:5002"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service.default.svc.cluster.local:5003"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: saranrnair/products-service:v2 # Updated image reference
          imagePullPolicy: Always
          ports:
            - containerPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-service
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations-service
  template:
    metadata:
      labels:
        app: recommendations-service
    spec:
      containers:
        - name: recommendations-service
          image: saranrnair/recommendations-service:v2 # Updated image reference
          imagePullPolicy: Always
          ports:
            - containerPort: 5002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: saranrnair/payment-service:v2 # Updated image reference
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
