apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: e-commerce  # Correct namespace
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: e-commerce  # Correct namespace
spec:
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: e-commerce  # Correct namespace
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
  namespace: e-commerce  # Correct namespace
spec:
  selector:
    app: recommendations-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: e-commerce  # Correct namespace
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003