apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: obs
  labels:
    object: visualization
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: LoadBalancer