apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: obs
  labels:
    app: mimir
spec:
  ports:
  - name: http
    port: 9009
    targetPort: http
  - name: grpc
    port: 9095
    targetPort: grpc
  selector:
    app: mimir
  type: ClusterIP