---
- name: Install pip packages
  hosts: otel_collector_vm
  become: true
  tasks:


    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure the 'universe' repository is enabled
      apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} universe"
            state: present

    - name: Install python3-pip
      apt:
          name: python3-pip
          state: present

    - name: Install required pip packages
      pip:
        name:
          - requests
          - flask
          - numpy
          - fastapi
          - flask
          - uvicorn
          # - azure-monitor-opentelemetry
          - opentelemetry-distro
          - opentelemetry-exporter-otlp
        state: present

    - name: List all installed pip packages
      command: pip list
      register: pip_packages

    - name: Print pip packages
      debug:
        var: pip_packages.stdout

