apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: e-commerce
  labels:
    app: loki
spec:
  ports:
  - name: http
    port: 3100
    targetPort: http
  - name: grpc
    port: 9096
    targetPort: grpc
  selector:
    app: loki
    component: read