apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: e-commerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector.e-commerce.svc.cluster.local:9464']
