apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: e-commerce
spec:
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer