apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: obs
  labels:
    object: tracing
spec:
  type: LoadBalancer
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: zipkin