apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: obs
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'null'

      routes:
      - receiver: 'email-critical'
        match:
          severity: "critical"
        continue: true

    receivers:
    - name: 'null'  # The "blackhole" receiver - drops alerts.


    - name: 'email-critical'
      email_configs:
      - to: 'sarannnair001@gmail.com'
        from: 'alertmanager@example.com'
        smarthost: 'mailhog.obs.svc.cluster.local:25'
        require_tls: false

    inhibit_rules: #example
      - source_matchers:
          - severity = 'critical'
        target_matchers:
          - severity = 'warning'
        equal: ['alertname', 'instance']

    # templates: # Uncomment and configure if you want custom email/notification templates
    # - 'templates/*.tmpl'