apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: obs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        ports:
        - name: smtp
          containerPort: 1025
        - name: http
          containerPort: 8025
