apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: obs
spec:
  type: LoadBalancer  # Exposes the service externally
  ports:
    - name: smtp
      port: 25
      targetPort: 1025
    - name: web
      port: 8025
      targetPort: 8025
  selector:
    app: mailhog