apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: obs
spec:
  selector:
    app: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: web
      protocol: TCP
  type: LoadBalancer