---
- name: Configure OpenTelemetry Collector and Prometheus
  hosts: otel_collector_vm
  become: yes
  roles:
    # - otel_collector
    - prometheus
    # - grafana

  vars_files:
    - ../roles/prometheus/vars/vars.yml
    - ../roles/otel_collector/vars/vars.yml
    - ../roles/grafana/vars/vars.yml
