apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: obs
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      k8sattributes:
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name

    connectors:
      routing:
        default_pipelines: [traces/debug]
        table:
          - context: resource
            condition: 'attributes["k8s.namespace.name"] == "voting-app"'
            pipelines: [traces/voting-app]
          - context: resource
            condition: 'attributes["k8s.namespace.name"] == "shopping-app"'
            pipelines: [traces/shopping-app]

    exporters:
      debug:
              verbosity: detailed  
      prometheus:
              endpoint: 0.0.0.0:9464
      zipkin/nontls:
              endpoint: "http://zipkin.obs.svc.cluster.local:9411/api/v2/spans"
              format: proto
      azuremonitor:
              connection_string: "${APPLICATIONINSIGHTS_CONNECTION_STRING}"
      otlp:
              endpoint: "tempo.obs.svc.cluster.local:4317"
              tls:
                insecure: true
      otlphttp/loki:
              endpoint: "http://loki.obs.svc.cluster.local:3100/loki/api/v1/push"
      prometheusremotewrite:
              endpoint: "http://mimir.obs.svc.cluster.local:9009/api/v1/push"
              tls:
                insecure: true

    extensions:
      file_storage:
        directory: /var/lib/otelcol

    service:
      telemetry:
        logs:
          level: debug
      extensions: [file_storage]
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus, azuremonitor, prometheusremotewrite, debug]
        logs:
          receivers: [otlp]
          exporters: [otlphttp/loki, azuremonitor, debug]
        traces:
          receivers: [otlp]
          processors: [k8sattributes]
          exporters: [routing]
        traces/voting-app:
          receivers: [routing]
          exporters: [zipkin/nontls]
        traces/shopping-app:
          receivers: [routing]
          exporters: [azuremonitor, otlp]
        traces/debug:
          receivers: [routing]
          exporters: [debug]
