apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: obs
data:
  alerts.yml: |
    groups:
    - name: node-alerts
      rules:
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 70
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on instance {{ $labels.instance }}"
          description: "CPU usage is above 70% for 2 minutes."

      - alert: LowCPUUsage
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) < 70
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on instance {{ $labels.instance }}"
          description: "CPU usage is above 70% for 2 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Memory usage on instance {{ $labels.instance }}"
          description: "Memory usage is above 80% for more than 2 minutes."

      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / 1024 / 1024 / 1024) < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on instance {{ $labels.instance }}"
          description: "Available disk space is below 10GB for more than 5 minutes."

      - alert: HighLoadAverage
        expr: node_load1 / count(node_cpu_seconds_total{mode="system"}) by (instance) > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Load Average on {{ $labels.instance }}"
          description: "Load average per core is above 1.5 for more than 5 minutes."

      - alert: HighDiskIO
        expr: rate(node_disk_io_time_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Disk I/O on {{ $labels.instance }}"
          description: "Disk I/O time is consistently above 80% for more than 5 minutes."

      - alert: HighSwapUsage
        expr: (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 25
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High Swap Usage on {{ $labels.instance }}"
          description: "Swap usage is above 25% for more than 3 minutes."

      - alert: NodeDown
        expr: up{job="node-exporter"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Node Down: {{ $labels.instance }}"
          description: "The node is unreachable for more than 2 minutes."

      - alert: HighNetworkUsage
        expr: rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m]) > 125000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Network Usage on {{ $labels.instance }}"
          description: "Total network usage exceeds 1Gbps for more than 5 minutes."
