apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: obs
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s # Evaluate rules every 15 seconds.

    scrape_configs:

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector.obs.svc.cluster.local:9464']

      - job_name: 'kubelet'
        scheme: https
        metrics_path: /metrics/cadvisor
        authorization:
          type: Bearer
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
          - source_labels: [__meta_kubernetes_node_name]
            target_label: node_name

      - job_name: 'node-exporter'
        scheme: http
        kubernetes_sd_configs:
            - role: node
        relabel_configs:
            - source_labels: [__address__]
              regex: (.+):.*
              target_label: __address__
              replacement: $1:9100
            - source_labels: [__meta_kubernetes_node_name]
              target_label: instance