apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: obs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      securityContext: # Add this section
        fsGroup: 65534  # Use the dedicated service account
      containers:
      - name: prometheus
        image: prom/prometheus:latest  # Or a specific version
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.enable-lifecycle"
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
        resources: # Add resource requests and limits!
          requests:
            memory: "2Gi"  # Adjust as needed
            cpu: "500m"    # Adjust as needed
          limits:
              memory: "4Gi"
              cpu: "1000m"
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      - name: prometheus-storage-volume
        persistentVolumeClaim:  # Use a PVC for persistent storage!
          claimName: prometheus-data-pvc  # You need to create this PVC separately