apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: obs
spec:
  accessModes:
    - ReadWriteOnce  # Most common access mode
  resources:
    requests:
      storage: 10Gi  # Adjust the size as needed!  Start small and increase.
  storageClassName: default # Or specify a specific storage class