apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: obs
data:
  tempo.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3200
      # grpc_listen_port: 9096
    distributor:
      receivers:                           
        otlp:                      
          protocols:                     
            grpc:                         
              endpoint: 0.0.0.0:4317       
            http:                         
              endpoint: 0.0.0.0:4318     
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        zipkin:
          endpoint: 0.0.0.0:9411

    storage:
      trace:
        backend: local                   
        local:
          path: /var/tempo              
        wal:                        
          path: /var/tempo/wal          

    overrides:
      metrics_generator_processors: [service-graphs, span-metrics]  # Enable processors
      