apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: obs
data:
  tempo.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3200
      # grpc_listen_port: 9096
    distributor:
      receivers:                           
        otlp:                      
          protocols:                     
            grpc:                         
              endpoint: 0.0.0.0:4317       
            http:                         
              endpoint: 0.0.0.0:4318     
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        zipkin:
          endpoint: 0.0.0.0:9411

    storage:
      trace:
        backend: local                   
        local:
          path: /var/tempo              
        wal:                        
          path: /var/tempo/wal          

    overrides:
      metrics_generator_processors: [service-graphs, span-metrics]  # Enable processors

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: obs
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        runAsUser: 10001
        fsGroup: 10001
      containers:
      - name: tempo
        image: grafana/tempo:2.2.0  
        args:
        - -config.file=/etc/tempo/tempo.yaml
        ports:
        - containerPort: 3200  
          name: http
        - containerPort: 4317
          name: grpc-otlp
        - containerPort: 4318
          name: http-otlp
        - containerPort: 14250
          name: jaeger-grpc
        - containerPort: 6832
          name: jaeger-binary
        - containerPort: 6831
          name: jaeger-compact
        - containerPort: 14268
          name: jaeger-http
        - containerPort: 9411
          name: zipkin
        volumeMounts:
        - name: tempo-config-vol
          mountPath: /etc/tempo
        - name: tempo-storage
          mountPath: /var/tempo
        readinessProbe:
          httpGet:
            path: /status 
            port: http
          initialDelaySeconds: 45
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 45
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: tempo-config-vol
        configMap:
          name: tempo-config
      - name: tempo-storage
        persistentVolumeClaim:
          claimName: tempo-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-storage
  namespace: obs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  
  storageClassName: default

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: obs
  labels:
    app: tempo
spec:
  ports:
  - name: http
    port: 3200       
    targetPort: http  
  - name: grpc-otlp
    port: 4317
    targetPort: grpc-otlp
  - name: http-otlp
    port: 4318
    targetPort: http-otlp
  - name: jaeger-grpc
    port: 14250
    targetPort: jaeger-grpc
  - name: jaeger-binary
    port: 6832
    targetPort: jaeger-binary
  - name: jaeger-compact
    port: 6831
    targetPort: jaeger-compact
  - name: jaeger-http
    port: 14268
    targetPort: jaeger-http
  - name: zipkin
    port: 9411
    targetPort: zipkin
  selector:
    app: tempo
  type: ClusterIP