apiVersion: v1
kind: Namespace
metadata:
  name: shopping-app
  labels:
    name: shopping-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: voting-app
  labels:
    name: voting-app
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: obs