apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: shopping-app
  labels:
    service: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: saranrnair/orders-service:v2@sha256:660cfc46572dee4282827727639200a60f9d5d23bc73f29ac370db1572c36741
          # image: gftotelshoppingapp.azurecr.io/orders-service:rfv1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PRODUCTS_SERVICE_URL
              value: "http://products-service.shopping-app.svc.cluster.local:5001"
            - name: RECOMMENDATIONS_SERVICE_URL
              value: "http://recommendations-service.shopping-app.svc.cluster.local:5002"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service.shopping-app.svc.cluster.local:5003"

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: shopping-app
spec:
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000