apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shopping-app
  labels:
    service: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: saranrnair/payment-service:v2@sha256:4f080a4d4af434deffe512ad9f8d8b722841e67d445196eee64cf9b749892a95
          # image: gftotelshoppingapp.azurecr.io/payment-service:rfv1
          imagePullPolicy: Always
          ports:
            - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: shopping-app
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003