apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-service
  namespace: shopping-app
  labels:
    service: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations-service
  template:
    metadata:
      labels:
        app: recommendations-service
    spec:
      containers:
        - name: recommendations-service
          image: saranrnair/recommendations-service:v2@sha256:de3dceb469be6387f2268807cbed7315cd506744a47bf82c238769be10daded3
          # image: gftotelshoppingapp.azurecr.io/recommendations-service:rfv1
          imagePullPolicy: Always
          ports:
            - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
  namespace: shopping-app
spec:
  selector:
    app: recommendations-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002