apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-service
  namespace: shopping-app
  labels:
    service: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendations-service
  template:
    metadata:
      labels:
        app: recommendations-service
    spec:
      containers:
        - name: recommendations-service
          image: saranrnair/recommendations-service:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
  namespace: shopping-app
spec:
  selector:
    app: recommendations-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002