apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed

      zipkin/nontls:
        endpoint: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
        format: proto
        default_service_name: voting-app

      azuremonitor:
        connection_string: "InstrumentationKey=5c0cba60-882e-4d31-8d60-134e754e8870;IngestionEndpoint=https://ingestion.azuremonitor.com/"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [zipkin/nontls, debug]
        metrics:
          receivers: [otlp]
          exporters: [azuremonitor, debug]
        logs:
          receivers: [otlp]
          exporters: [debug]
