apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocol: grpc:
        host: 0.0.0.0
        port: 4317
      kubeletstats:
        insecure_skip_verify: true

    processors:
      batch:

    exporters:
      azuremonitor:
        instrumentation_key: "InstrumentationKey=5c0cba60-882e-4d31-8d60-134e754e8870;IngestionEndpoint=https://ingestion.azuremonitor.com/"

      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuremonitor, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuremonitor, logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuremonitor, logging]
