apiVersion: v1
kind: PersistentVolume
metadata:
  name: otel-collector-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/otel-collector

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-collector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
