apiVersion: v1
kind: Service
metadata:
  name: loki-write
  namespace: default
  labels:
    app: loki
    component: write
spec:
  ports:
  - name: http
    port: 3100
    targetPort: http
  - name: grpc
    port: 9096
    targetPort: grpc
  selector:
    app: loki
    component: write
  type: ClusterIP