apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: obs
  labels:
    object: open-telemetry
spec:
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: prometheus
      port: 9464
      targetPort: 9464
      protocol: TCP
  selector:
    app: otel-collector