apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: obs
  labels:
    object: tracing
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 5775
      targetPort: 5775
    - name: compact
      port: 5776
      targetPort: 5776
    - name: thrift-http
      port: 5778
      targetPort: 5778
    - name: jaeger-collector
      port: 14250
      targetPort: 14250
    - name: jaeger-query
      port: 16686
      targetPort: 16686
    - name: jaeger-tracing
      port: 6831
      targetPort: 6831
    - name: jaeger-tracing-udp
      port: 6832
      targetPort: 6832
    - name: zipkin
      port: 9411
      targetPort: 9411
  selector:
    app: jaeger-all-in-one